### ISSUE TITLE
Change the format of sharing on Twitter

### ISSUE THREAD

**Issue by ooade** [JonathanSpeek/tech-confessions#14]
It's just an opinion. Here's what It currently shows:
![current_confession](https://user-images.githubusercontent.com/11811904/43680222-fb8cdc96-982c-11e8-9d6d-158829dd883a.png)

And, here's what I feel it should look like:
![future_confession](https://user-images.githubusercontent.com/11811904/43680226-0a441b3c-982d-11e8-8449-d03a0b67af9e.png)

The content should come first IMO.
I can send in PR if you don't mind.
Nice project BTW :+1:

**Comment by JonathanSpeek** [comment]
I agree, feel free to send in a PR if you want 👍
